# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vkladki4.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

import xlwt, xlrd
from PyQt5 import QtCore, QtGui, QtWidgets
i = int
j = int 

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(800, 626)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 141, 20))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 101, 20))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 181, 20))
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(20, 0, 181, 20))
        self.label_11.setObjectName("label_11")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(160, 60, 321, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(130, 20, 351, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(250, 140, 231, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_4.setGeometry(QtCore.QRect(490, 80, 91, 23))
        self.textEdit_4.setObjectName("textEdit_4")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(130, 100, 351, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_5.setGeometry(QtCore.QRect(490, 100, 91, 23))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(490, 40, 91, 23))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 120, 191, 20))
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 131, 20))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 111, 20))
        self.label_8.setObjectName("label_8")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(140, 80, 341, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(490, 20, 91, 23))
        self.textEdit.setObjectName("textEdit")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 140, 211, 20))
        self.label_10.setObjectName("label_10")
        self.textEdit_8 = QtWidgets.QTextEdit(self.tab)
        
        self.textEdit_8.setGeometry(QtCore.QRect(490, 0, 91, 23))
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_6.setGeometry(QtCore.QRect(490, 120, 91, 23))
        self.textEdit_6.setObjectName("textEdit_6")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(120, 40, 361, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(140, 0, 341, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_7.setGeometry(QtCore.QRect(490, 140, 91, 23))
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_3.setGeometry(QtCore.QRect(490, 60, 91, 23))
        self.textEdit_3.setObjectName("textEdit_3")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(210, 120, 271, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(640, 550, 101, 23))
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton.clicked.connect(self.showDialog)
        '''
        self.pushButton.clicked.connect(self.BtnPushed)
        self.pushButton.clicked.connect(self.BtnPushed2)
        showDialog'''

        self.line_54 = QtWidgets.QFrame(self.tab)
        self.line_54.setGeometry(QtCore.QRect(430, 260, 51, 20))
        self.line_54.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_54.setObjectName("line_54")
        self.line_55 = QtWidgets.QFrame(self.tab)
        self.line_55.setGeometry(QtCore.QRect(80, 160, 401, 20))
        self.line_55.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_55.setObjectName("line_55")
        self.textEdit_54 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_54.setGeometry(QtCore.QRect(490, 200, 91, 23))
        self.textEdit_54.setObjectName("textEdit_54")
        self.line_56 = QtWidgets.QFrame(self.tab)
        self.line_56.setGeometry(QtCore.QRect(420, 240, 61, 20))
        self.line_56.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.label_69 = QtWidgets.QLabel(self.tab)
        self.label_69.setGeometry(QtCore.QRect(20, 220, 221, 20))
        self.label_69.setObjectName("label_69")
        self.textEdit_55 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_55.setGeometry(QtCore.QRect(490, 260, 91, 23))
        self.textEdit_55.setObjectName("textEdit_55")
        self.line_57 = QtWidgets.QFrame(self.tab)
        self.line_57.setGeometry(QtCore.QRect(150, 180, 331, 20))
        self.line_57.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_57.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_57.setObjectName("line_57")
        self.textEdit_56 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_56.setGeometry(QtCore.QRect(490, 180, 91, 23))
        self.textEdit_56.setObjectName("textEdit_56")
        self.label_70 = QtWidgets.QLabel(self.tab)
        self.label_70.setGeometry(QtCore.QRect(20, 160, 61, 20))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.tab)
        self.label_71.setGeometry(QtCore.QRect(20, 280, 411, 20))
        self.label_71.setObjectName("label_71")
        self.textEdit_57 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_57.setGeometry(QtCore.QRect(490, 220, 91, 23))
        self.textEdit_57.setObjectName("textEdit_57")
        self.line_58 = QtWidgets.QFrame(self.tab)
        self.line_58.setGeometry(QtCore.QRect(250, 200, 231, 20))
        self.line_58.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_58.setObjectName("line_58")
        self.line_59 = QtWidgets.QFrame(self.tab)
        self.line_59.setGeometry(QtCore.QRect(440, 300, 51, 20))
        self.line_59.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_59.setObjectName("line_59")
        self.line_60 = QtWidgets.QFrame(self.tab)
        self.line_60.setGeometry(QtCore.QRect(250, 220, 231, 20))
        self.line_60.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_60.setObjectName("line_60")
        self.label_72 = QtWidgets.QLabel(self.tab)
        self.label_72.setGeometry(QtCore.QRect(20, 200, 221, 20))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.tab)
        self.label_73.setGeometry(QtCore.QRect(20, 260, 411, 20))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab)
        self.label_74.setGeometry(QtCore.QRect(20, 180, 121, 20))
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.tab)
        self.label_75.setGeometry(QtCore.QRect(20, 300, 421, 20))
        self.label_75.setObjectName("label_75")
        self.textEdit_58 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_58.setGeometry(QtCore.QRect(490, 280, 91, 23))
        self.textEdit_58.setObjectName("textEdit_58")
        self.line_61 = QtWidgets.QFrame(self.tab)
        self.line_61.setGeometry(QtCore.QRect(440, 280, 41, 20))
        self.line_61.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_61.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_61.setObjectName("line_61")
        self.textEdit_59 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_59.setGeometry(QtCore.QRect(490, 240, 91, 23))
        self.textEdit_59.setObjectName("textEdit_59")
        self.textEdit_60 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_60.setGeometry(QtCore.QRect(490, 160, 91, 23))
        self.textEdit_60.setObjectName("textEdit_60")
        self.label_76 = QtWidgets.QLabel(self.tab)
        self.label_76.setGeometry(QtCore.QRect(20, 240, 401, 20))
        self.label_76.setObjectName("label_76")
        self.textEdit_61 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_61.setGeometry(QtCore.QRect(490, 300, 91, 23))
        self.textEdit_61.setObjectName("textEdit_61")
        self.label_77 = QtWidgets.QLabel(self.tab)
        self.label_77.setGeometry(QtCore.QRect(20, 480, 201, 20))
        self.label_77.setObjectName("label_77")
        self.line_62 = QtWidgets.QFrame(self.tab)
        self.line_62.setGeometry(QtCore.QRect(240, 420, 241, 20))
        self.line_62.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_62.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_62.setObjectName("line_62")
        self.line_63 = QtWidgets.QFrame(self.tab)
        self.line_63.setGeometry(QtCore.QRect(140, 320, 341, 20))
        self.line_63.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_63.setObjectName("line_63")
        self.textEdit_62 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_62.setGeometry(QtCore.QRect(490, 360, 91, 23))
        self.textEdit_62.setObjectName("textEdit_62")
        self.line_64 = QtWidgets.QFrame(self.tab)
        self.line_64.setGeometry(QtCore.QRect(140, 400, 341, 20))
        self.line_64.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_64.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_64.setObjectName("line_64")
        self.label_78 = QtWidgets.QLabel(self.tab)
        self.label_78.setGeometry(QtCore.QRect(20, 380, 141, 20))
        self.label_78.setObjectName("label_78")
        self.textEdit_63 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_63.setGeometry(QtCore.QRect(490, 420, 91, 23))
        self.textEdit_63.setObjectName("textEdit_63")
        self.line_65 = QtWidgets.QFrame(self.tab)
        self.line_65.setGeometry(QtCore.QRect(410, 340, 71, 20))
        self.line_65.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_65.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_65.setObjectName("line_65")
        self.textEdit_64 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_64.setGeometry(QtCore.QRect(490, 340, 91, 23))
        self.textEdit_64.setObjectName("textEdit_64")
        self.textEdit_65 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_65.setGeometry(QtCore.QRect(490, 480, 91, 23))
        self.textEdit_65.setObjectName("textEdit_65")
        self.label_79 = QtWidgets.QLabel(self.tab)
        self.label_79.setGeometry(QtCore.QRect(20, 320, 181, 20))
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.tab)
        self.label_80.setGeometry(QtCore.QRect(20, 440, 211, 20))
        self.label_80.setObjectName("label_80")
        self.textEdit_66 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_66.setGeometry(QtCore.QRect(490, 380, 91, 23))
        self.textEdit_66.setObjectName("textEdit_66")
        self.line_66 = QtWidgets.QFrame(self.tab)
        self.line_66.setGeometry(QtCore.QRect(180, 360, 301, 20))
        self.line_66.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_66.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_66.setObjectName("line_66")
        self.line_67 = QtWidgets.QFrame(self.tab)
        self.line_67.setGeometry(QtCore.QRect(240, 460, 241, 20))
        self.line_67.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_67.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_67.setObjectName("line_67")
        self.line_68 = QtWidgets.QFrame(self.tab)
        self.line_68.setGeometry(QtCore.QRect(170, 380, 311, 20))
        self.line_68.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_68.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_68.setObjectName("line_68")
        self.label_81 = QtWidgets.QLabel(self.tab)
        self.label_81.setGeometry(QtCore.QRect(20, 360, 161, 20))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.tab)
        self.label_82.setGeometry(QtCore.QRect(20, 420, 201, 20))
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.tab)
        self.label_83.setGeometry(QtCore.QRect(20, 340, 381, 20))
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.tab)
        self.label_84.setGeometry(QtCore.QRect(20, 460, 211, 20))
        self.label_84.setObjectName("label_84")
        self.textEdit_67 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_67.setGeometry(QtCore.QRect(490, 440, 91, 23))
        self.textEdit_67.setObjectName("textEdit_67")
        self.line_69 = QtWidgets.QFrame(self.tab)
        self.line_69.setGeometry(QtCore.QRect(240, 440, 241, 20))
        self.line_69.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_69.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_69.setObjectName("line_69")
        self.textEdit_68 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_68.setGeometry(QtCore.QRect(490, 400, 91, 23))
        self.textEdit_68.setObjectName("textEdit_68")
        self.textEdit_69 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_69.setGeometry(QtCore.QRect(490, 320, 91, 23))
        self.textEdit_69.setObjectName("textEdit_69")
        self.label_85 = QtWidgets.QLabel(self.tab)
        self.label_85.setGeometry(QtCore.QRect(660, 500, 61, 20))
        self.label_85.setObjectName("label_85")
        self.line_70 = QtWidgets.QFrame(self.tab)
        self.line_70.setGeometry(QtCore.QRect(240, 480, 241, 20))
        self.line_70.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_70.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_70.setObjectName("line_70")
        self.textEdit_70 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_70.setGeometry(QtCore.QRect(490, 460, 91, 23))
        self.textEdit_70.setObjectName("textEdit_70")
        self.textEdit_71 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_71.setGeometry(QtCore.QRect(490, 540, 91, 23))
        self.textEdit_71.setObjectName("textEdit_71")
        self.line_71 = QtWidgets.QFrame(self.tab)
        self.line_71.setGeometry(QtCore.QRect(240, 540, 241, 20))
        self.line_71.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_71.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_71.setObjectName("line_71")
        self.label_86 = QtWidgets.QLabel(self.tab)
        self.label_86.setGeometry(QtCore.QRect(20, 540, 211, 20))
        self.label_86.setObjectName("label_86")
        self.line_72 = QtWidgets.QFrame(self.tab)
        self.line_72.setGeometry(QtCore.QRect(240, 560, 241, 20))
        self.line_72.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_72.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_72.setObjectName("line_72")
        self.textEdit_72 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_72.setGeometry(QtCore.QRect(490, 500, 91, 23))
        self.textEdit_72.setObjectName("textEdit_72")
        self.textEdit_73 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_73.setGeometry(QtCore.QRect(490, 520, 91, 23))
        self.textEdit_73.setObjectName("textEdit_73")
        self.line_73 = QtWidgets.QFrame(self.tab)
        self.line_73.setGeometry(QtCore.QRect(240, 500, 241, 20))
        self.line_73.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_73.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_73.setObjectName("line_73")
        self.label_87 = QtWidgets.QLabel(self.tab)
        self.label_87.setGeometry(QtCore.QRect(20, 520, 211, 20))
        self.label_87.setObjectName("label_87")
        self.textEdit_74 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_74.setGeometry(QtCore.QRect(490, 560, 91, 23))
        self.textEdit_74.setObjectName("textEdit_74")
        self.label_88 = QtWidgets.QLabel(self.tab)
        self.label_88.setGeometry(QtCore.QRect(20, 500, 201, 20))
        self.label_88.setObjectName("label_88")
        self.line_74 = QtWidgets.QFrame(self.tab)
        self.line_74.setGeometry(QtCore.QRect(240, 520, 241, 20))
        self.line_74.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_74.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_74.setObjectName("line_74")
        self.label_89 = QtWidgets.QLabel(self.tab)
        self.label_89.setGeometry(QtCore.QRect(20, 560, 211, 20))
        self.label_89.setObjectName("label_89")
        '''
        self.textEdit_75 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_75.setGeometry(QtCore.QRect(640, 520, 101, 23))
        self.textEdit_75.setObjectName("textEdit_75")
        '''
        self.label_90 = QtWidgets.QLabel(self.tab)
        self.label_90.setGeometry(QtCore.QRect(20, 400, 141, 20))
        self.label_90.setObjectName("label_90")
        TabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 751, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(0, -10, 161, 301))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("эскиз1.PNG"))
        self.label_17.setObjectName("label_17")
        self.line_12 = QtWidgets.QFrame(self.tab_5)
        self.line_12.setGeometry(QtCore.QRect(220, 20, 231, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.textEdit_12 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_12.setGeometry(QtCore.QRect(450, 20, 71, 23))
        self.textEdit_12.setObjectName("textEdit_12")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(170, 20, 81, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(170, 40, 181, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(170, 60, 181, 20))
        self.label_24.setObjectName("label_24")
        self.textEdit_13 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_13.setGeometry(QtCore.QRect(450, 60, 71, 23))
        self.textEdit_13.setObjectName("textEdit_13")
        self.line_13 = QtWidgets.QFrame(self.tab_5)
        self.line_13.setGeometry(QtCore.QRect(340, 60, 111, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.tab_5)
        self.line_14.setGeometry(QtCore.QRect(220, 40, 231, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.textEdit_14 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_14.setGeometry(QtCore.QRect(450, 40, 71, 23))
        self.textEdit_14.setObjectName("textEdit_14")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(0, 0, 161, 271))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("эскиз2.png"))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(350, 10, 81, 20))
        self.label_19.setObjectName("label_19")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_9.setGeometry(QtCore.QRect(630, 10, 71, 23))
        self.textEdit_9.setObjectName("textEdit_9")
        self.line_9 = QtWidgets.QFrame(self.tab_6)
        self.line_9.setGeometry(QtCore.QRect(400, 10, 231, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_10.setGeometry(QtCore.QRect(630, 30, 71, 23))
        self.textEdit_10.setObjectName("textEdit_10")
        self.line_10 = QtWidgets.QFrame(self.tab_6)
        self.line_10.setGeometry(QtCore.QRect(400, 30, 231, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(350, 30, 181, 20))
        self.label_20.setObjectName("label_20")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_11.setGeometry(QtCore.QRect(630, 50, 71, 23))
        self.textEdit_11.setObjectName("textEdit_11")
        self.line_11 = QtWidgets.QFrame(self.tab_6)
        self.line_11.setGeometry(QtCore.QRect(520, 50, 111, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setGeometry(QtCore.QRect(350, 50, 181, 20))
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setGeometry(QtCore.QRect(0, 0, 221, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label.setObjectName("label")
        self.line_15 = QtWidgets.QFrame(self.tab_7)
        self.line_15.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.textEdit_15 = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_15.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_15.setObjectName("textEdit_15")
        self.label_25 = QtWidgets.QLabel(self.tab_7)
        self.label_25.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_7)
        self.label_27.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_27.setObjectName("label_27")
        self.textEdit_16 = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_16.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_16.setObjectName("textEdit_16")
        self.line_16 = QtWidgets.QFrame(self.tab_7)
        self.line_16.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.tab_7)
        self.line_17.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.textEdit_17 = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_17.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_17.setObjectName("textEdit_17")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_3 = QtWidgets.QLabel(self.tab_8)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 221, 211))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_3.setObjectName("label_3")
        self.line_18 = QtWidgets.QFrame(self.tab_8)
        self.line_18.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.textEdit_18 = QtWidgets.QTextEdit(self.tab_8)
        self.textEdit_18.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_18.setObjectName("textEdit_18")
        self.label_28 = QtWidgets.QLabel(self.tab_8)
        self.label_28.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_8)
        self.label_29.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_8)
        self.label_30.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_30.setObjectName("label_30")
        self.textEdit_19 = QtWidgets.QTextEdit(self.tab_8)
        self.textEdit_19.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_19.setObjectName("textEdit_19")
        self.line_19 = QtWidgets.QFrame(self.tab_8)
        self.line_19.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.tab_8)
        self.line_20.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.textEdit_20 = QtWidgets.QTextEdit(self.tab_8)
        self.textEdit_20.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_20.setObjectName("textEdit_20")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_4 = QtWidgets.QLabel(self.tab_9)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 221, 231))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_4.setObjectName("label_4")
        self.line_21 = QtWidgets.QFrame(self.tab_9)
        self.line_21.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.textEdit_21 = QtWidgets.QTextEdit(self.tab_9)
        self.textEdit_21.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_21.setObjectName("textEdit_21")
        self.label_31 = QtWidgets.QLabel(self.tab_9)
        self.label_31.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_9)
        self.label_32.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_9)
        self.label_33.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_33.setObjectName("label_33")
        self.textEdit_22 = QtWidgets.QTextEdit(self.tab_9)
        self.textEdit_22.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_22.setObjectName("textEdit_22")
        self.line_22 = QtWidgets.QFrame(self.tab_9)
        self.line_22.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(self.tab_9)
        self.line_23.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.textEdit_23 = QtWidgets.QTextEdit(self.tab_9)
        self.textEdit_23.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_23.setObjectName("textEdit_23")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_12 = QtWidgets.QLabel(self.tab_10)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 221, 211))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_12.setObjectName("label_12")
        self.line_24 = QtWidgets.QFrame(self.tab_10)
        self.line_24.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.textEdit_24 = QtWidgets.QTextEdit(self.tab_10)
        self.textEdit_24.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_24.setObjectName("textEdit_24")
        self.label_34 = QtWidgets.QLabel(self.tab_10)
        self.label_34.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_10)
        self.label_35.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_10)
        self.label_36.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_36.setObjectName("label_36")
        self.textEdit_25 = QtWidgets.QTextEdit(self.tab_10)
        self.textEdit_25.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_25.setObjectName("textEdit_25")
        self.line_25 = QtWidgets.QFrame(self.tab_10)
        self.line_25.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.line_26 = QtWidgets.QFrame(self.tab_10)
        self.line_26.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.textEdit_26 = QtWidgets.QTextEdit(self.tab_10)
        self.textEdit_26.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_26.setObjectName("textEdit_26")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_13 = QtWidgets.QLabel(self.tab_11)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 221, 211))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_13.setObjectName("label_13")
        self.line_27 = QtWidgets.QFrame(self.tab_11)
        self.line_27.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.textEdit_27 = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_27.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_27.setObjectName("textEdit_27")
        self.label_37 = QtWidgets.QLabel(self.tab_11)
        self.label_37.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_11)
        self.label_38.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_11)
        self.label_39.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_39.setObjectName("label_39")
        self.textEdit_28 = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_28.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_28.setObjectName("textEdit_28")
        self.line_28 = QtWidgets.QFrame(self.tab_11)
        self.line_28.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(self.tab_11)
        self.line_29.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.textEdit_29 = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_29.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_29.setObjectName("textEdit_29")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.label_14 = QtWidgets.QLabel(self.tab_12)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 231, 211))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_14.setObjectName("label_14")
        self.line_30 = QtWidgets.QFrame(self.tab_12)
        self.line_30.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.textEdit_30 = QtWidgets.QTextEdit(self.tab_12)
        self.textEdit_30.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_30.setObjectName("textEdit_30")
        self.label_40 = QtWidgets.QLabel(self.tab_12)
        self.label_40.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_12)
        self.label_41.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_12)
        self.label_42.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_42.setObjectName("label_42")
        self.textEdit_31 = QtWidgets.QTextEdit(self.tab_12)
        self.textEdit_31.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_31.setObjectName("textEdit_31")
        self.line_31 = QtWidgets.QFrame(self.tab_12)
        self.line_31.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.line_32 = QtWidgets.QFrame(self.tab_12)
        self.line_32.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.textEdit_32 = QtWidgets.QTextEdit(self.tab_12)
        self.textEdit_32.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_32.setObjectName("textEdit_32")
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.label_15 = QtWidgets.QLabel(self.tab_13)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 221, 221))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_15.setObjectName("label_15")
        self.line_33 = QtWidgets.QFrame(self.tab_13)
        self.line_33.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.textEdit_33 = QtWidgets.QTextEdit(self.tab_13)
        self.textEdit_33.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_33.setObjectName("textEdit_33")
        self.label_43 = QtWidgets.QLabel(self.tab_13)
        self.label_43.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_13)
        self.label_44.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_13)
        self.label_45.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_45.setObjectName("label_45")
        self.textEdit_34 = QtWidgets.QTextEdit(self.tab_13)
        self.textEdit_34.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_34.setObjectName("textEdit_34")
        self.line_34 = QtWidgets.QFrame(self.tab_13)
        self.line_34.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.line_35 = QtWidgets.QFrame(self.tab_13)
        self.line_35.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.textEdit_35 = QtWidgets.QTextEdit(self.tab_13)
        self.textEdit_35.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_35.setObjectName("textEdit_35")
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.label_16 = QtWidgets.QLabel(self.tab_14)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 221, 221))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_16.setObjectName("label_16")
        self.line_36 = QtWidgets.QFrame(self.tab_14)
        self.line_36.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_36.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.textEdit_36 = QtWidgets.QTextEdit(self.tab_14)
        self.textEdit_36.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_36.setObjectName("textEdit_36")
        self.label_46 = QtWidgets.QLabel(self.tab_14)
        self.label_46.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_14)
        self.label_47.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_14)
        self.label_48.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_48.setObjectName("label_48")
        self.textEdit_37 = QtWidgets.QTextEdit(self.tab_14)
        self.textEdit_37.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_37.setObjectName("textEdit_37")
        self.line_37 = QtWidgets.QFrame(self.tab_14)
        self.line_37.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.line_38 = QtWidgets.QFrame(self.tab_14)
        self.line_38.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.textEdit_38 = QtWidgets.QTextEdit(self.tab_14)
        self.textEdit_38.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_38.setObjectName("textEdit_38")
        self.tabWidget.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.line_39 = QtWidgets.QFrame(self.tab_15)
        self.line_39.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.textEdit_39 = QtWidgets.QTextEdit(self.tab_15)
        self.textEdit_39.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_39.setObjectName("textEdit_39")
        self.label_49 = QtWidgets.QLabel(self.tab_15)
        self.label_49.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_15)
        self.label_50.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_15)
        self.label_51.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_51.setObjectName("label_51")
        self.textEdit_40 = QtWidgets.QTextEdit(self.tab_15)
        self.textEdit_40.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_40.setObjectName("textEdit_40")
        self.line_40 = QtWidgets.QFrame(self.tab_15)
        self.line_40.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.line_41 = QtWidgets.QFrame(self.tab_15)
        self.line_41.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.textEdit_41 = QtWidgets.QTextEdit(self.tab_15)
        self.textEdit_41.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_41.setObjectName("textEdit_41")
        self.label_64 = QtWidgets.QLabel(self.tab_15)
        self.label_64.setGeometry(QtCore.QRect(0, 0, 221, 231))
        self.label_64.setText("")
        self.label_64.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_64.setObjectName("label_64")
        self.tabWidget.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.line_42 = QtWidgets.QFrame(self.tab_16)
        self.line_42.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_42.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.textEdit_42 = QtWidgets.QTextEdit(self.tab_16)
        self.textEdit_42.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_42.setObjectName("textEdit_42")
        self.label_52 = QtWidgets.QLabel(self.tab_16)
        self.label_52.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_16)
        self.label_53.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_16)
        self.label_54.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_54.setObjectName("label_54")
        self.textEdit_43 = QtWidgets.QTextEdit(self.tab_16)
        self.textEdit_43.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_43.setObjectName("textEdit_43")
        self.line_43 = QtWidgets.QFrame(self.tab_16)
        self.line_43.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.line_44 = QtWidgets.QFrame(self.tab_16)
        self.line_44.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.textEdit_44 = QtWidgets.QTextEdit(self.tab_16)
        self.textEdit_44.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_44.setObjectName("textEdit_44")
        self.label_65 = QtWidgets.QLabel(self.tab_16)
        self.label_65.setGeometry(QtCore.QRect(0, 0, 221, 231))
        self.label_65.setText("")
        self.label_65.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_65.setObjectName("label_65")
        self.tabWidget.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.line_45 = QtWidgets.QFrame(self.tab_17)
        self.line_45.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.textEdit_45 = QtWidgets.QTextEdit(self.tab_17)
        self.textEdit_45.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_45.setObjectName("textEdit_45")
        self.label_55 = QtWidgets.QLabel(self.tab_17)
        self.label_55.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_17)
        self.label_56.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_17)
        self.label_57.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_57.setObjectName("label_57")
        self.textEdit_46 = QtWidgets.QTextEdit(self.tab_17)
        self.textEdit_46.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_46.setObjectName("textEdit_46")
        self.line_46 = QtWidgets.QFrame(self.tab_17)
        self.line_46.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_46.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.line_47 = QtWidgets.QFrame(self.tab_17)
        self.line_47.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_47.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.textEdit_47 = QtWidgets.QTextEdit(self.tab_17)
        self.textEdit_47.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_47.setObjectName("textEdit_47")
        self.label_66 = QtWidgets.QLabel(self.tab_17)
        self.label_66.setGeometry(QtCore.QRect(0, 0, 221, 231))
        self.label_66.setText("")
        self.label_66.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_66.setObjectName("label_66")
        self.tabWidget.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.line_48 = QtWidgets.QFrame(self.tab_18)
        self.line_48.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_48.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.textEdit_48 = QtWidgets.QTextEdit(self.tab_18)
        self.textEdit_48.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_48.setObjectName("textEdit_48")
        self.label_58 = QtWidgets.QLabel(self.tab_18)
        self.label_58.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_18)
        self.label_59.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_18)
        self.label_60.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_60.setObjectName("label_60")
        self.textEdit_49 = QtWidgets.QTextEdit(self.tab_18)
        self.textEdit_49.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_49.setObjectName("textEdit_49")
        self.line_49 = QtWidgets.QFrame(self.tab_18)
        self.line_49.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_49.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.line_50 = QtWidgets.QFrame(self.tab_18)
        self.line_50.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_50.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.textEdit_50 = QtWidgets.QTextEdit(self.tab_18)
        self.textEdit_50.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_50.setObjectName("textEdit_50")
        self.label_67 = QtWidgets.QLabel(self.tab_18)
        self.label_67.setGeometry(QtCore.QRect(0, 0, 221, 231))
        self.label_67.setText("")
        self.label_67.setPixmap(QtGui.QPixmap("Desktop/проекты/1.PNG"))
        self.label_67.setObjectName("label_67")
        self.tabWidget.addTab(self.tab_18, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.line_51 = QtWidgets.QFrame(self.tab_19)
        self.line_51.setGeometry(QtCore.QRect(440, 0, 231, 20))
        self.line_51.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.textEdit_51 = QtWidgets.QTextEdit(self.tab_19)
        self.textEdit_51.setGeometry(QtCore.QRect(670, 0, 71, 23))
        self.textEdit_51.setObjectName("textEdit_51")
        self.label_61 = QtWidgets.QLabel(self.tab_19)
        self.label_61.setGeometry(QtCore.QRect(390, 0, 81, 20))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_19)
        self.label_62.setGeometry(QtCore.QRect(390, 20, 181, 20))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_19)
        self.label_63.setGeometry(QtCore.QRect(390, 40, 181, 20))
        self.label_63.setObjectName("label_63")
        self.textEdit_52 = QtWidgets.QTextEdit(self.tab_19)
        self.textEdit_52.setGeometry(QtCore.QRect(670, 40, 71, 23))
        self.textEdit_52.setObjectName("textEdit_52")
        self.line_52 = QtWidgets.QFrame(self.tab_19)
        self.line_52.setGeometry(QtCore.QRect(560, 40, 111, 20))
        self.line_52.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.line_53 = QtWidgets.QFrame(self.tab_19)
        self.line_53.setGeometry(QtCore.QRect(440, 20, 231, 20))
        self.line_53.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_53.setObjectName("line_53")
        self.textEdit_53 = QtWidgets.QTextEdit(self.tab_19)
        self.textEdit_53.setGeometry(QtCore.QRect(670, 20, 71, 23))
        self.textEdit_53.setObjectName("textEdit_53")
        self.label_68 = QtWidgets.QLabel(self.tab_19)
        self.label_68.setGeometry(QtCore.QRect(0, 0, 221, 251))
        self.label_68.setText("")
        self.label_68.setPixmap(QtGui.QPixmap("н1.PNG"))
        self.label_68.setObjectName("label_68")
        self.tabWidget.addTab(self.tab_19, "")
        TabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        TabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        TabWidget.addTab(self.tab_3, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        self.label_7.setText(_translate("TabWidget", "Толщина стенки в мм"))
        self.label_5.setText(_translate("TabWidget", "Вид заготовки"))
        self.label_2.setText(_translate("TabWidget", "Профиль заготовки"))
        self.label_11.setText(_translate("TabWidget", "<html><head/><body><p>Код материала детали</p></body></html>"))
        self.textEdit_2.setToolTip(_translate("TabWidget", "<html><head/><body><p>10 или 11 квалитет ....</p><p>13 квалитет и грубее при....</p></body></html>"))
        self.label_9.setText(_translate("TabWidget", "Вид химико термической обработки"))
        self.label_6.setText(_translate("TabWidget", "Диаметр заготовки в мм"))
        self.label_8.setText(_translate("TabWidget", "Длина заготовки в мм"))
        self.textEdit.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_10.setText(_translate("TabWidget", "Глубина химико-термической обработки"))
        self.textEdit_8.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_3.setToolTip(_translate("TabWidget", "<html><head/><body><p>1- .....</p><p>2- .....</p><p>3- .....</p></body></html>"))
        self.pushButton.setText(_translate("TabWidget", "Сохранить"))
        self.textEdit_54.setToolTip(_translate("TabWidget", "<html><head/><body><p>10 или 11 квалитет ....</p><p>13 квалитет и грубее при....</p></body></html>"))
        self.label_69.setText(_translate("TabWidget", "Наличие центров с правой стороны детали"))
        self.textEdit_56.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_70.setText(_translate("TabWidget", "<html><head/><body><p>Твердость</p></body></html>"))
        self.label_71.setText(_translate("TabWidget", "Кол-во элементов 1-го уровня в левой части внутренней конфигурации детали"))
        self.textEdit_57.setToolTip(_translate("TabWidget", "<html><head/><body><p>1- .....</p><p>2- .....</p><p>3- .....</p></body></html>"))
        self.label_72.setText(_translate("TabWidget", "Наличие центров с левой стороны детали"))
        self.label_73.setText(_translate("TabWidget", "Кол-во элементов 1-го уровня в правой части наружной конфигурации детали"))
        self.label_74.setText(_translate("TabWidget", "Код и размер покрытия"))
        self.label_75.setText(_translate("TabWidget", "Кол-во элементов 1-го уровня в правой части внутренней конфигурации детали"))
        self.textEdit_60.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_76.setText(_translate("TabWidget", "Кол-во элементов 1-го уровня в левой части наружной конфигурации детали"))
        self.label_77.setText(_translate("TabWidget", "<html><head/><body><p>Кол-во занятых столбцов массива ТМ7</p></body></html>"))
        self.textEdit_62.setToolTip(_translate("TabWidget", "<html><head/><body><p>10 или 11 квалитет ....</p><p>13 квалитет и грубее при....</p></body></html>"))
        self.label_78.setText(_translate("TabWidget", "Масса готовой детали в кг"))
        self.textEdit_64.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_65.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_79.setText(_translate("TabWidget", "<html><head/><body><p>Длина детали в мм</p></body></html>"))
        self.label_80.setText(_translate("TabWidget", "Кол-во занятых столбцов массива ТМД"))
        self.textEdit_66.setToolTip(_translate("TabWidget", "<html><head/><body><p>1- .....</p><p>2- .....</p><p>3- .....</p></body></html>"))
        self.label_81.setText(_translate("TabWidget", "Кол-во деталей из заготовки"))
        self.label_82.setText(_translate("TabWidget", "Кол-во занятых столбцов массива ТМ3"))
        self.label_83.setText(_translate("TabWidget", "Код типа станка токарной группы применяемого для первой операции ТП"))
        self.label_84.setText(_translate("TabWidget", "Кол-во занятых столбцов массива ТМ2"))
        self.textEdit_69.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_85.setText(_translate("TabWidget", ""))
        self.label_86.setText(_translate("TabWidget", "Кол-во занятых столбцов массива ТМДТ"))
        self.label_87.setText(_translate("TabWidget", "Кол-во занятых столбцов массива ТМ10"))
        self.textEdit_74.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_88.setText(_translate("TabWidget", "Кол-во занятых столбцов массива ТМ8"))
        self.label_89.setText(_translate("TabWidget", "<html><head/><body><p>Кол-во занятых столбцов массива ТМДП</p></body></html>"))
        self.label_90.setText(_translate("TabWidget", "Масса заготовки в кг"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Общие сведения о детали(ТМ1)"))
        self.textEdit_12.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_22.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_23.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_24.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_13.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_14.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("TabWidget", "Левый торец"))
        self.label_19.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.textEdit_9.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_10.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_20.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.textEdit_11.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_21.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("TabWidget", "Правый торец"))
        self.textEdit_15.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_25.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_26.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_27.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_16.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_17.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("TabWidget", "3-й"))
        self.textEdit_18.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_28.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_29.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_30.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_19.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_20.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("TabWidget", "4-й"))
        self.textEdit_21.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_31.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_32.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_33.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_22.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_23.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("TabWidget", "5-й"))
        self.textEdit_24.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_34.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_35.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_36.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_25.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_26.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("TabWidget", "6-й"))
        self.textEdit_27.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_37.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_38.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_39.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_28.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_29.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("TabWidget", "7-й"))
        self.textEdit_30.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_40.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_41.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_42.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_31.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_32.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("TabWidget", "8-й"))
        self.textEdit_33.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_43.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_44.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_45.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_34.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_35.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("TabWidget", "9-й"))
        self.textEdit_36.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_46.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_47.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_48.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_37.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_38.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("TabWidget", "10-й"))
        self.textEdit_39.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_49.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_50.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_51.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_40.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_41.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("TabWidget", "11-й"))
        self.textEdit_42.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_52.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_53.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_54.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_43.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_44.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_16), _translate("TabWidget", "12-й"))
        self.textEdit_45.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_55.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_56.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_57.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_46.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_47.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_17), _translate("TabWidget", "13-й"))
        self.textEdit_48.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_58.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_59.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_60.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_49.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_50.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_18), _translate("TabWidget", "14-й"))
        self.textEdit_51.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.label_61.setText(_translate("TabWidget", "<html><head/><body><p>Диаметр</p></body></html>"))
        self.label_62.setText(_translate("TabWidget", "<html><head/><body><p>Посадка</p></body></html>"))
        self.label_63.setText(_translate("TabWidget", "<html><head/><body><p>Химико-термическая обработка</p></body></html>"))
        self.textEdit_52.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.textEdit_53.setToolTip(_translate("TabWidget", "<html><head/><body><p>Если они имеются</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_19), _translate("TabWidget", "15-й"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_4), _translate("TabWidget", "Элементы вращения первого уровня(ТМ2)"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "Страница"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "Страница"))
        
    def BtnPushed2(self, TabWidget):
        import xlrd
        print('ok2')
        #save2 = self.textEdit_75.toPlainText()
        chtenie = xlrd.open_workbook('file' + '.xls', formatting_info=True)

        #выбираем активный лист
        sheetch = chtenie.sheet_by_index(0)

        k = int
        j = int
        knl = int
        knp = int
        kvl = int
        kvp  = int
        knlt = int
        nemd = int
        kne = int
        koe1 = int
        nso  = int
        nepvp = int
        nepvl = int
        neso = int
        knl = sheetch.row_values(12)[1]
        knp = sheetch.row_values(13)[1]
        kvl = sheetch.row_values(14)[1]
        kvp = sheetch.row_values(15)[1]
        knl = int(knl)
        knp = int(knp)
        kvl = int(kvl)
        kvp = int(kvp)

        knlt = 2 + knl
        nemd = 2 + knl +1
        kne = 2 + knl + knp
        neso = 2 + knl + knp + kvl + 1
        koe1 = 2 + knl + knp + kvl + kvp
        nepvl = 2 + knl + knp +kvl
        nepvp = 2 + knl +knp +kvl + 1
        nso = 0
        
        


        def algoritm(i):
            
            
            if i == 1:
                j = 100
            elif i == 2:
                j = 200
            elif i <= koe1:
                if i == nemd:
                    if i == 3:
                        if i == kne:
                            j = 1
                        else:
                            j = 2
                    else:
                        if i == kne:
                            j = 3
                        else:
                            j = 4
                else:
                    if i <= kne:
                        if i < nemd:
                            j = 5
                        else:
                            j = 6
                    else:
                        if nso == 1:
                            if neso == 2+knl+knp+kvl+1:
                                if i == neso:
                                    if kvl == 0:
                                        if kvp == 1:
                                            j = 7
                                        else:
                                            j = 8
                                    else:
                                        if kvp == 1:
                                            j = 9
                                        else:
                                            j = 10
                                else:
                                    if i < neso:
                                        j = 11
                                    else:
                                       j = 12
                            else:
                                j = 0
                        else:
                            if kvl == 0:
                                if nepvp == 2 + knl +knp +kvl + 1:
                                    if i == nepvp:
                                        if kvp == 1:
                                            j = 13
                                        else:
                                            j = 14
                                    else:
                                        j = 12
                                else:
                                    j = 0
                            else:
                                if kvp == 0:
                                    if nepvl == 2 + knl + knp + kvl:
                                        if i == nepvl:
                                            if kvl == 1:
                                                j = 15
                                            else:
                                                j = 16
                                        else:
                                            j = 11
                                    else:
                                        j = 0
                                else:
                                    if nepvl == 2 + knl + knp + kvl and nepvp == 2 + knl + knp + kvl + 1:
                                        if i > nepvl:
                                            if i == nepvp:
                                                if kvp == 1:
                                                    j = 13
                                                else:
                                                    j = 14
                                            else:
                                                j = 12
                                        else:
                                            if i == nepvl:
                                                if kvl == 1:
                                                    j = 15
                                                else:
                                                    j = 16
                                            else:
                                                j = 11
                                    else:
                                        j = 0 
    
            else:
                j = 0
        #0 ошибка
        #100 левый торец
        #200 правый торец 
            return(j)

        
        
        
        
        if algoritm(3) == 1:
            self.label.setPixmap(QtGui.QPixmap("1.PNG"))
        elif algoritm(3) == 2:
            self.label.setPixmap(QtGui.QPixmap("2.PNG"))
        elif algoritm(3) == 3:
            self.label.setPixmap(QtGui.QPixmap("3.PNG"))
        elif algoritm(3) == 4:
            self.label.setPixmap(QtGui.QPixmap("4.PNG"))
        elif algoritm(3) == 5:
            self.label.setPixmap(QtGui.QPixmap("5.PNG"))
        elif algoritm(3) == 6:
            self.label.setPixmap(QtGui.QPixmap("6.PNG"))
        elif algoritm(3) == 7:
            self.label.setPixmap(QtGui.QPixmap("7.PNG"))
        elif algoritm(3) == 8:
            self.label.setPixmap(QtGui.QPixmap("8.PNG"))
        elif algoritm(3) == 9:
            self.label.setPixmap(QtGui.QPixmap("8.PNG"))
        elif algoritm(3) == 10:
            self.label.setPixmap(QtGui.QPixmap("10.PNG"))
        elif algoritm(3) == 11:
            self.label.setPixmap(QtGui.QPixmap("11.PNG"))
        elif algoritm(3) == 12:
            self.label.setPixmap(QtGui.QPixmap("12.PNG"))
        elif algoritm(3) == 13:
            self.label.setPixmap(QtGui.QPixmap("13.PNG"))
        elif algoritm(3) == 14:
            self.label.setPixmap(QtGui.QPixmap("14.PNG"))
        elif algoritm(3) == 15:
            self.label.setPixmap(QtGui.QPixmap("15.PNG"))
        elif algoritm(3) == 16:
            self.label.setPixmap(QtGui.QPixmap("16.PNG"))
        else:
            None

        if algoritm(4) == 1:
            self.label_3.setPixmap(QtGui.QPixmap("1.PNG"))
        elif algoritm(4) == 2:
            self.label_3.setPixmap(QtGui.QPixmap("2.PNG"))
        elif algoritm(4) == 3:
            self.label_3.setPixmap(QtGui.QPixmap("3.PNG"))
        elif algoritm(4) == 4:
            self.label_3.setPixmap(QtGui.QPixmap("4.PNG"))
        elif algoritm(4) == 5:
            self.label_3.setPixmap(QtGui.QPixmap("5.PNG"))
        elif algoritm(4) == 6:
            self.label_3.setPixmap(QtGui.QPixmap("6.PNG"))
        elif algoritm(4) == 7:
            self.label_3.setPixmap(QtGui.QPixmap("7.PNG"))
        elif algoritm(4) == 8:
            self.label_3.setPixmap(QtGui.QPixmap("8.PNG"))
        elif algoritm(4) == 9:
            self.label_3.setPixmap(QtGui.QPixmap("8.PNG"))
        elif algoritm(4) == 10:
            self.label_3.setPixmap(QtGui.QPixmap("10.PNG"))
        elif algoritm(4) == 11:
            self.label_3.setPixmap(QtGui.QPixmap("11.PNG"))
        elif algoritm(4) == 12:
            self.label_3.setPixmap(QtGui.QPixmap("12.PNG"))
        elif algoritm(4) == 13:
            self.label_3.setPixmap(QtGui.QPixmap("13.PNG"))
        elif algoritm(4) == 14:
            self.label_3.setPixmap(QtGui.QPixmap("14.PNG"))
        elif algoritm(4) == 15:
            self.label_3.setPixmap(QtGui.QPixmap("15.PNG"))
        elif algoritm(4) == 16:
            self.label_3.setPixmap(QtGui.QPixmap("16.PNG"))
        else:
            None

        if algoritm(5) == 1:
            self.label_4.setPixmap(QtGui.QPixmap("1.PNG"))
        elif algoritm(5) == 2:
            self.label_4.setPixmap(QtGui.QPixmap("2.PNG"))
        elif algoritm(5) == 3:
            self.label_4.setPixmap(QtGui.QPixmap("3.PNG"))
        elif algoritm(5) == 4:
            self.label_4.setPixmap(QtGui.QPixmap("4.PNG"))
        elif algoritm(5) == 5:
            self.label_4.setPixmap(QtGui.QPixmap("5.PNG"))
        elif algoritm(5) == 6:
            self.label_4.setPixmap(QtGui.QPixmap("6.PNG"))
        elif algoritm(5) == 7:
            self.label_4.setPixmap(QtGui.QPixmap("7.PNG"))
        elif algoritm(5) == 8:
            self.label_4.setPixmap(QtGui.QPixmap("8.PNG"))
        elif algoritm(5) == 9:
            self.label_4.setPixmap(QtGui.QPixmap("8.PNG"))
        elif algoritm(5) == 10:
            self.label_4.setPixmap(QtGui.QPixmap("10.PNG"))
        elif algoritm(5) == 11:
            self.label_4.setPixmap(QtGui.QPixmap("11.PNG"))
        elif algoritm(5) == 12:
            self.label_4.setPixmap(QtGui.QPixmap("12.PNG"))
        elif algoritm(5) == 13:
            self.label_4.setPixmap(QtGui.QPixmap("13.PNG"))
        elif algoritm(5) == 14:
            self.label_4.setPixmap(QtGui.QPixmap("14.PNG"))
        elif algoritm(5) == 15:
            self.label_4.setPixmap(QtGui.QPixmap("15.PNG"))
        elif algoritm(5) == 16:
            self.label_4.setPixmap(QtGui.QPixmap("16.PNG"))
        else:
            None

        if algoritm(6) == 1:
            self.label_12.setPixmap(QtGui.QPixmap("1.PNG"))
        elif algoritm(6) == 2:
            self.label_12.setPixmap(QtGui.QPixmap("2.PNG"))
        elif algoritm(6) == 3:
            self.label_12.setPixmap(QtGui.QPixmap("3.PNG"))
        elif algoritm(6) == 4:
            self.label_12.setPixmap(QtGui.QPixmap("4.PNG"))
        elif algoritm(6) == 5:
            self.label_12.setPixmap(QtGui.QPixmap("5.PNG"))
        elif algoritm(6) == 6:
            self.label_12.setPixmap(QtGui.QPixmap("6.PNG"))
        elif algoritm(6) == 7:
            self.label_12.setPixmap(QtGui.QPixmap("7.PNG"))
        elif algoritm(6) == 8:
            self.label_12.setPixmap(QtGui.QPixmap("8.PNG"))
        elif algoritm(6) == 9:
            self.label_12.setPixmap(QtGui.QPixmap("8.PNG"))
        elif algoritm(6) == 10:
            self.label_12.setPixmap(QtGui.QPixmap("10.PNG"))
        elif algoritm(6) == 11:
            self.label_12.setPixmap(QtGui.QPixmap("11.PNG"))
        elif algoritm(6) == 12:
            self.label_12.setPixmap(QtGui.QPixmap("12.PNG"))
        elif algoritm(6) == 13:
            self.label_12.setPixmap(QtGui.QPixmap("13.PNG"))
        elif algoritm(6) == 14:
            self.label_12.setPixmap(QtGui.QPixmap("14.PNG"))
        elif algoritm(6) == 15:
            self.label_12.setPixmap(QtGui.QPixmap("15.PNG"))
        elif algoritm(6) == 16:
            self.label_12.setPixmap(QtGui.QPixmap("16.PNG"))
        else:
            None




        
    def showDialog(self, TabWidget):
        
        def g(self):
            print('lol')

        text, ok = QtWidgets.QInputDialog.getText(self.tab, 'Сохранение данных',
            'Название файла:')

        if ok:
            print('1')
            self.BtnPushed(1)
            self.BtnPushed2(1)
        

    def BtnPushed(self, TabWidget):
        print ('ok1')
        text1 = self.textEdit_8.toPlainText()
        text2 = self.textEdit.toPlainText()
        text3 = self.textEdit_2.toPlainText()
        text4 = self.textEdit_3.toPlainText()
        text5 = self.textEdit_4.toPlainText()
        text6 = self.textEdit_5.toPlainText()
        text7 = self.textEdit_6.toPlainText()
        text8 = self.textEdit_7.toPlainText()
        text9 = self.textEdit_60.toPlainText()
        text10 = self.textEdit_56.toPlainText()
        text11 = self.textEdit_54.toPlainText()
        text12 = self.textEdit_57.toPlainText()
        text13 = self.textEdit_59.toPlainText()
        text14 = self.textEdit_55.toPlainText()
        text15 = self.textEdit_58.toPlainText()
        text16 = self.textEdit_61.toPlainText()
        text17 = self.textEdit_69.toPlainText()
        text18 = self.textEdit_64.toPlainText()
        text19 = self.textEdit_62.toPlainText()
        text20 = self.textEdit_66.toPlainText()
        text21 = self.textEdit_68.toPlainText()
        text22 = self.textEdit_63.toPlainText()
        text23 = self.textEdit_67.toPlainText()
        text24 = self.textEdit_70.toPlainText()
        text25 = self.textEdit_65.toPlainText()
        text26 = self.textEdit_72.toPlainText()
        text27 = self.textEdit_73.toPlainText()
        text28 = self.textEdit_71.toPlainText()
        text29 = self.textEdit_74.toPlainText()

        
        workbook = xlwt.Workbook()
        sheet=workbook.add_sheet('TM1')
        sheet2=workbook.add_sheet('TM2')
        sheet3=workbook.add_sheet('TM3')
        sheet4=workbook.add_sheet('TM4')
        sheet.write(0,0, 'kod m.')
        sheet.write(1,0, 'prof.z.')
        sheet.write(2,0, 'vid z.')
        sheet.write(3,0, 'diam z.')
        sheet.write(4,0, 'tolsh.st.')
        sheet.write(5,0, 'dlina z.')
        sheet.write(6,0, 'him.term.')
        sheet.write(7,0, 'gl.him.term.')
        sheet.write(8,0, 'tverd.')
        sheet.write(9,0, 'pokr.')
        sheet.write(10,0, 'centr.lev.')
        sheet.write(11,0, 'centr.prav')
        sheet.write(12,0, 'knl')
        sheet.write(13,0, 'knp')
        sheet.write(14,0, 'kvl')
        sheet.write(15,0, 'kvp')
        sheet.write(16,0, 'dlina d.')
        sheet.write(17,0, 'tip st.')
        sheet.write(18,0, 'kolvo d.')
        sheet.write(19,0, 'm d.')
        sheet.write(20,0, 'm z.')
        sheet.write(21,0, 'st.TM3')
        sheet.write(22,0, 'st.TMD')
        sheet.write(23,0, 'st.TM2')
        sheet.write(24,0, 'st.TM7')
        sheet.write(25,0, 'st.TM8')
        sheet.write(26,0, 'st.TM10')
        sheet.write(27,0, 'st.TMDT')
        sheet.write(28,0, 'st.TMDP')
        
        sheet.write(0, 1, text1)
        sheet.write(1, 1, text2)
        sheet.write(2, 1, text3)
        sheet.write(3, 1, text4)
        sheet.write(4, 1, text5)
        sheet.write(5, 1, text6)
        sheet.write(6, 1, text7)
        sheet.write(7, 1, text8)
        sheet.write(8, 1, text9)
        sheet.write(9, 1, text10)
        sheet.write(10, 1, text11)
        sheet.write(11, 1, text12)
        sheet.write(12, 1, text13)
        sheet.write(13, 1, text14)
        sheet.write(14, 1, text15)
        sheet.write(15, 1, text16)
        sheet.write(16, 1, text17)
        sheet.write(17, 1, text18)
        sheet.write(18, 1, text19)
        sheet.write(19, 1, text20)
        sheet.write(20, 1, text21)
        sheet.write(21, 1, text22)
        sheet.write(22, 1, text23)
        sheet.write(23, 1, text24)
        sheet.write(24, 1, text25)
        sheet.write(25, 1, text26)
        sheet.write(26, 1, text27)
        sheet.write(27, 1, text28)
        sheet.write(28, 1, text29)
        
        
        workbook.save('file' + '.xls')




if __name__ == "__main__":
    import sys
    


    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
